import pancakes from './Images/pancakes.png';
import soup from './Images/soup.png';

const MealsList = [
  // ===== SNÍDANĚ =====
  {
    id: 1,
    name: "Palačinky z banánů a bílků",
    image: pancakes,
    emoji: "🥞",
    ingredients: [
      { name: "Vaječné bílky", amount: "3 ks" },
      { name: "Banán", amount: "½ ks" },
      { name: "Ořechové máslo", amount: "1 lžíce" },
      { name: "Skořice", amount: "špetka" },
    ],
    instructions: "Rozmixujeme všechny ingredience a upečeme na teflonové pánvi.",
    type: "breakfast",
    preparation: "Smažení",
  },
  {
    id: 2,
    name: "Ovesná kaše s jablkem a skořicí",
    image: null,
    emoji: "🍚",
    ingredients: [
      { name: "Ovesné vločky", amount: "80 g" },
      { name: "Mléko", amount: "200 ml" },
      { name: "Jablko", amount: "1 ks" },
      { name: "Skořice", amount: "1 lžičky" },
      { name: "Med", amount: "1 lžičky" },
    ],
    instructions: "Vločky uvaříme v mléce, přidáme nastrouhané jablko a skořici, přesladíme medem.",
    type: "breakfast",
    preparation: "Vaření",
  },
  {
    id: 3,
    name: "Míchaná vejce se zeleninou",
    image: null,
    emoji: "🍳",
    ingredients: [
      { name: "Vejce", amount: "3 ks" },
      { name: "Paprika", amount: "½ ks" },
      { name: "Rajče", amount: "1 ks" },
      { name: "Čerstvý špenát", amount: "hrst" },
      { name: "Olivový olej", amount: "1 lžičky" },
      { name: "Sůl, pepř", amount: "dle chuti" },
    ],
    instructions: "Na oleji osmažíme zeleninu, přidáme rozšlehaná vejce a mícháme do tuhé.",
    type: "breakfast",
    preparation: "Smažení",
  },
  {
    id: 4,
    name: "Jogurt parfait s granolou",
    image: null,
    emoji: "🥛",
    ingredients: [
      { name: "Řecký jogurt", amount: "200 g" },
      { name: "Granola", amount: "50 g" },
      { name: "Lesní ovoce", amount: "hrst" },
      { name: "Med", amount: "1 lžičky" },
    ],
    instructions: "Vrstvíme jogurt, granolu a ovoce, pokapeme medem.",
    type: "breakfast",
    preparation: "Bez vaření",
  },
  {
    id: 5,
    name: "Toast s avokádem a vejcem",
    image: null,
    emoji: "🥑",
    ingredients: [
      { name: "Celozrnný chléb", amount: "2 plátky" },
      { name: "Avokádo", amount: "½ ks" },
      { name: "Vejce", amount: "1 ks" },
      { name: "Citronová šťáva", amount: "pár kapek" },
      { name: "Sůl, pepř", amount: "dle chuti" },
      { name: "Chilli vločky", amount: "dle chuti" },
    ],
    instructions: "Chleba opečeme, rozmačkáme avokádo s citronem a solí, navrch položíme volské oko.",
    type: "breakfast",
    preparation: "Smažení",
  },

  // ===== SVAČINA =====
  {
    id: 6,
    name: "Jablko s mandlovým máslem",
    image: null,
    emoji: "🍎",
    ingredients: [
      { name: "Jablko", amount: "1 ks" },
      { name: "Mandlové máslo", amount: "2 lžíce" },
    ],
    instructions: "Jablko nakrájíme na plátky, podáváme s mandlovým máslem.",
    type: "snack",
    preparation: "Bez vaření",
  },
  {
    id: 7,
    name: "Tvaroh s ovocem",
    image: null,
    emoji: "🍓",
    ingredients: [
      { name: "Tvaroh", amount: "150 g" },
      { name: "Jahody nebo borůvky", amount: "hrst" },
      { name: "Med", amount: "1 lžičky" },
    ],
    instructions: "Smícháme tvaroh s ovocem, přesladíme medem.",
    type: "snack",
    preparation: "Bez vaření",
  },
  {
    id: 8,
    name: "Ořechy a sušené ovoce",
    image: null,
    emoji: "🥜",
    ingredients: [
      { name: "Vlašské ořechy", amount: "30 g" },
      { name: "Mandle", amount: "20 g" },
      { name: "Sušené meruňky", amount: "30 g" },
    ],
    instructions: "Smícháme a pojídáme jako rychlou svačinu.",
    type: "snack",
    preparation: "Bez vaření",
  },
  {
    id: 9,
    name: "Rýžový chlebíček s cottage sýrem",
    image: null,
    emoji: "🍞",
    ingredients: [
      { name: "Rýžové chlebíčky", amount: "3 ks" },
      { name: "Cottage sýr", amount: "100 g" },
      { name: "Pažitka", amount: "hrst" },
      { name: "Rajče", amount: "½ ks" },
    ],
    instructions: "Chlebíčky pomažeme cottage sýrem, posypeme pažitkou a přidáme nakrájené rajče.",
    type: "snack",
    preparation: "Bez vaření",
  },

  // ===== OBĚD =====
  {
    id: 10,
    name: "Zeleninová polévka s kuřecím masem",
    image: soup,
    emoji: "🍲",
    ingredients: [
      { name: "Kuřecí prsa", amount: "150 g" },
      { name: "Celer", amount: "kus" },
      { name: "Petržel", amount: "2 ks" },
      { name: "Mrkev", amount: "2 ks" },
      { name: "Cibule", amount: "1 ks" },
      { name: "Česnek", amount: "2 stroužky" },
      { name: "Sůl, pepř", amount: "dle chuti" },
    ],
    instructions: "Maso uvaříme v osolené vodě s cibulí a česnekem. Před koncem nastrouhejte kořenovou zeleninu. Posypeme petrželí.",
    type: "lunch",
    preparation: "Vaření",
  },
  {
    id: 11,
    name: "Kuřecí steak s rýží a brokolicí",
    image: null,
    emoji: "🍗",
    ingredients: [
      { name: "Kuřecí prsa", amount: "200 g" },
      { name: "Rýže", amount: "80 g" },
      { name: "Brokolice", amount: "200 g" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Sůl, pepř, paprika", amount: "dle chuti" },
    ],
    instructions: "Rýži uvaříme. Kuřecí prsa okořeníme a opečeme na oleji. Brokolici uvaříme nebo podusíme.",
    type: "lunch",
    preparation: "Vaření + Smažení",
  },
  {
    id: 12,
    name: "Těstoviny Bolognese",
    image: null,
    emoji: "🍝",
    ingredients: [
      { name: "Špagety", amount: "100 g" },
      { name: "Mleté hovězí maso", amount: "150 g" },
      { name: "Rajčatová passata", amount: "200 ml" },
      { name: "Cibule", amount: "1 ks" },
      { name: "Česnek", amount: "2 stroužky" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Bazalka, oregano", amount: "dle chuti" },
    ],
    instructions: "Osmažíme cibuli a česnek, přidáme maso a opečeme. Přilijeme passatu, dusíme 15 min. Podáváme s uvařenými těstovinami.",
    type: "lunch",
    preparation: "Vaření + Smažení",
  },
  {
    id: 13,
    name: "Losos se zeleninou a brambory",
    image: null,
    emoji: "🐟",
    ingredients: [
      { name: "Losos (filé)", amount: "180 g" },
      { name: "Brambory", amount: "200 g" },
      { name: "Cuketa", amount: "1 ks" },
      { name: "Citron", amount: "½ ks" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Sůl, pepř, kopr", amount: "dle chuti" },
    ],
    instructions: "Brambory uvaříme. Lososa a cuket upečeme v troubě při 180 °C po dobu 20 minut. Podáváme s citronem.",
    type: "lunch",
    preparation: "Pečení",
  },
  {
    id: 14,
    name: "Čočková polévka",
    image: soup,
    emoji: "🍛",
    ingredients: [
      { name: "Červená čočka", amount: "150 g" },
      { name: "Mrkev", amount: "2 ks" },
      { name: "Cibule", amount: "1 ks" },
      { name: "Česnek", amount: "2 stroužky" },
      { name: "Kmín, kurkuma", amount: "1 lžičky" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Sůl", amount: "dle chuti" },
    ],
    instructions: "Osmažíme cibuli a česnek, přidáme koření, čočku a zeleninu. Zalijeme vodou a vaříme 20 min.",
    type: "lunch",
    preparation: "Vaření",
  },
  {
    id: 15,
    name: "Kuřecí Caesar salát",
    image: null,
    emoji: "🥗",
    ingredients: [
      { name: "Kuřecí prsa", amount: "150 g" },
      { name: "Římský salát", amount: "200 g" },
      { name: "Parmazán", amount: "30 g" },
      { name: "Krutony", amount: "hrst" },
      { name: "Caesar dresink", amount: "3 lžíce" },
    ],
    instructions: "Kuře opečeme a nakrájíme. Smícháme se salátem, parmazánem a krutonami. Polijeme dresinkem.",
    type: "lunch",
    preparation: "Smažení",
  },

  // ===== ODPOLEDNÍ SVAČINA =====
  {
    id: 16,
    name: "Tvarohový dip se zeleninou",
    image: null,
    emoji: "🥦",
    ingredients: [
      { name: "Tvaroh", amount: "150 g" },
      { name: "Mrkev", amount: "2 ks" },
      { name: "Okurka", amount: "½ ks" },
      { name: "Paprika", amount: "½ ks" },
      { name: "Pažitka, sůl, pepř", amount: "dle chuti" },
    ],
    instructions: "Tvaroh okořeníme pažitkou, solí a pepřem. Podáváme s nakrájenou zeleninou.",
    type: "afternoon_snack",
    preparation: "Bez vaření",
  },
  {
    id: 17,
    name: "Ovocný salát",
    image: null,
    emoji: "🍉",
    ingredients: [
      { name: "Jahody", amount: "100 g" },
      { name: "Borůvky", amount: "80 g" },
      { name: "Banán", amount: "1 ks" },
      { name: "Kiwi", amount: "1 ks" },
      { name: "Citronová šťáva", amount: "pár kapek" },
    ],
    instructions: "Nakrájíme ovoce a smícháme, pokapeme citronovou šťávou.",
    type: "afternoon_snack",
    preparation: "Bez vaření",
  },
  {
    id: 18,
    name: "Proteinový shake s banánem",
    image: null,
    emoji: "🥤",
    ingredients: [
      { name: "Proteinový prášek", amount: "30 g" },
      { name: "Banán", amount: "1 ks" },
      { name: "Mléko nebo mandlové mléko", amount: "250 ml" },
    ],
    instructions: "Vše rozmixujeme v mixéru dohladka.",
    type: "afternoon_snack",
    preparation: "Bez vaření",
  },

  // ===== VEČEŘE =====
  {
    id: 19,
    name: "Kuřecí prsa s bylinkami a špenátem",
    image: null,
    emoji: "🍗",
    ingredients: [
      { name: "Kuřecí prsa", amount: "200 g" },
      { name: "Čerstvý špenát", amount: "150 g" },
      { name: "Česnek", amount: "2 stroužky" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Tymián, rozmarýn", amount: "dle chuti" },
      { name: "Sůl, pepř", amount: "dle chuti" },
    ],
    instructions: "Kuřecí prsa okořeníme bylinkami a opečeme na oleji. Na stejné pánvi osmažíme česnek a přidáme špenát.",
    type: "dinner",
    preparation: "Smažení",
  },
  {
    id: 20,
    name: "Vepřová panenka s pečenou zeleninou",
    image: null,
    emoji: "🥩",
    ingredients: [
      { name: "Vepřová panenka", amount: "200 g" },
      { name: "Batáty", amount: "200 g" },
      { name: "Cuketa", amount: "1 ks" },
      { name: "Červená paprika", amount: "1 ks" },
      { name: "Olivový olej", amount: "2 lžíce" },
      { name: "Sůl, pepř, oregano", amount: "dle chuti" },
    ],
    instructions: "Zeleninu nakrájíme, polijeme olejem, okořeníme a pečeme 25 min při 200 °C. Maso opečeme na pánvi.",
    type: "dinner",
    preparation: "Pečení + Smažení",
  },
  {
    id: 21,
    name: "Pečené rybí filé s citronem",
    image: null,
    emoji: "🐟",
    ingredients: [
      { name: "Bílé rybí filé (treska)", amount: "200 g" },
      { name: "Citron", amount: "½ ks" },
      { name: "Česnek", amount: "2 stroužky" },
      { name: "Olivový olej", amount: "1 lžíce" },
      { name: "Petržel", amount: "hrst" },
      { name: "Sůl, pepř", amount: "dle chuti" },
    ],
    instructions: "Filé ochutíme solí, pepřem, česnekem a citronem. Pečeme 15–20 min při 180 °C. Posypeme petrželí.",
    type: "dinner",
    preparation: "Pečení",
  },
  {
    id: 22,
    name: "Zeleninové curry s tofu",
    image: null,
    emoji: "🍛",
    ingredients: [
      { name: "Tofu", amount: "200 g" },
      { name: "Kokosové mléko", amount: "200 ml" },
      { name: "Cuketa", amount: "1 ks" },
      { name: "Mrkev", amount: "2 ks" },
      { name: "Cibule", amount: "1 ks" },
      { name: "Curry pasta", amount: "2 lžíce" },
      { name: "Rýže basmati", amount: "80 g" },
    ],
    instructions: "Osmažíme cibuli s curry pastou, přidáme zeleninu a tofu, zalijeme kokosovým mlékem. Vaříme 15 min. Podáváme s rýží.",
    type: "dinner",
    preparation: "Vaření",
  },
  {
    id: 23,
    name: "Pohankový salát s grilovaným kuřetem",
    image: null,
    emoji: "🥗",
    ingredients: [
      { name: "Pohanka", amount: "80 g" },
      { name: "Kuřecí prsa", amount: "150 g" },
      { name: "Rukola", amount: "hrst" },
      { name: "Rajče", amount: "2 ks" },
      { name: "Okurka", amount: "½ ks" },
      { name: "Olivový olej", amount: "2 lžíce" },
      { name: "Citronová šťáva", amount: "1 lžíce" },
    ],
    instructions: "Pohanka uvaříme. Kuřecí prsa ugrilujeme a nakrájíme. Smícháme se zeleninou, polijeme dresinkem.",
    type: "dinner",
    preparation: "Vaření + Grilování",
  },
];

export default MealsList;
